[tools]
python = "3.13"
vim = "latest"
uv = "latest"
pre-commit = "latest"
trivy = "latest"
ruff = "latest"
k3d = "latest"
kubectl = "latest"
k9s = "latest"
gh = "latest"
flux2 = "latest"

[settings]
python.uv_venv_auto = "create|source"
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'Study_App'
GITOPS_REPO = 'study-app-gitops'

[hooks]
enter = "bash ./scripts/setup_project"


[tasks.k8s-setup-local]
description = "Set up a basic Kubernetes cluster for development that builds the local images and applies them"
run = "./Kubernetes/setup_cluster_local"

[tasks.k8s-setup-minimal]
description = "Set up a minimal Kubernetes cluster for testing. Does not apply anything."
run = "./Kubernetes/setup_cluster_minimal"

[tasks.e2e-test]
description = "Run end-to-end tests on the Kubernetes deployment"
run = "cd ./Kubernetes && uv run e2e_test.py"

[tasks.setup-keys]
description = "Set up deploy keys for our repo"
run = "bash ./scripts/setup_deploy_keys"

[tasks.k8s-setup-gitops]
description = "Set up a cluster configured with GitOps using Flux"
run = "bash ./Kubernetes/setup_cluster_gitops"
